//
//  DetailModels.swift
//  themovies
//
//  Created by Luis Domingues on 03/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum MovieDetail {
        struct Request {
            let movieID: Int
        }
        
        struct Response {
            let poster: URL?
            let title: String
            let description: String
            let releaseDate: String
            let voteAverage: Double
            let runtime: Int
        }
        
        struct ViewModel {
            let poster: URL?
            let title: String
            let description: String
            let releaseDate: String
            let voteAverage: Double
            let runtime: String
        }
    }
}
