//
//  DetailInteractor.swift
//  themovies
//
//  Created by Luis Domingues on 03/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func doSomething(request: Detail.Something.Request)
}

protocol DetailDataStore {
//    var name: String { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    var coordinator: Coordinator?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Detail.Something.Request) {
        worker = DetailWorker()
        worker?.doSomeWork()
        
        let response = Detail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
