//
//  LoginStarterPresenter.swift
//  themovies
//
//  Created by Luis Domingues on 01/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginStarterPresentationLogic {
    func presentLoginFields()
}

class LoginStarterPresenter: LoginStarterPresentationLogic {
    weak var viewController: LoginStarterDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: LoginStarter.Something.Response) {
        let viewModel = LoginStarter.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentLoginFields() {
        viewController?.displayLoginFields()
    }
    
}
