//
//  HomeModels.swift
//  themovies
//
//  Created by Luis Domingues on 01/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
    
    enum MovieGenderFilter {
        struct Request {
            let indexClicked: Int
        }
        
        struct Response {
            let movies: [ContentMovie]
        }
        
        struct ViewModel {
            let movies: [ContentMovie]
        }
    }
    
}
