//
//  HomePresenter.swift
//  themovies
//
//  Created by Luis Domingues on 01/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentFilterThemes(response: Home.MovieGenderFilter.Response)
    func presentUpdatedSelection(response: Home.MovieGenderFilter.Response)
    func presentMoviesBanner(response: Home.MovieBanner.Response)
    func presentPopularMovies(response: Home.MovieBanner.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
        
    func presentFilterThemes(response: Home.MovieGenderFilter.Response) {
        let viewModel = Home.MovieGenderFilter.ViewModel(movies: response.movies)
        viewController?.displayFilterOptions(viewModel: viewModel)
    }
    
    func presentUpdatedSelection(response: Home.MovieGenderFilter.Response) {
        let viewModel = Home.MovieGenderFilter.ViewModel(movies: response.movies) 
        viewController?.displayClickedPill(viewModel: viewModel)
    }
    
    func presentMoviesBanner(response: Home.MovieBanner.Response) {
        let viewModel = Home.MovieBanner.ViewModel(images: response.images.results)
        viewController?.displayBanner(viewModel: viewModel)
    }
    
    func presentPopularMovies(response: Home.MovieBanner.Response) {
        let viewModel = Home.MovieBanner.ViewModel(images: response.images.results)
        viewController?.displayBanner(viewModel: viewModel)
    }
}
