//
//  HomeViewController.swift
//  themovies
//
//  Created by Luis Domingues on 01/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: AnyObject {
    func displayFilterOptions(viewModel: Home.MovieGenderFilter.ViewModel)
    func displayClickedPill(viewModel: Home.MovieGenderFilter.ViewModel)
    func displayBanner(viewModel: Home.MovieBanner.ViewModel)
    func displayStopPagination(viewModel: Home.Pagination.ViewModel)
}

struct ContentMovie {
    var isSelected: Bool
    let gender: String
    let type: MovieFilterType
}

enum MovieFilterType {
    case popularMovie
    case onAirMovie
    case popularSeries
    case onAirSeries
}

extension HomeViewController.Layout {
    enum FontSize: CGFloat {
        case small = 16
        case medium = 20
        case large = 28
    }
    
    enum ComponentSizes: CGFloat {
        case bannerWidth = 124
        case bannerHeight = 188
        case imageSize = 40
        case pillsHeight = 30
        case distance = 16
    }
    
    enum SpaceConstraints: CGFloat {
        case base01 = 16
        case base02 = 20
        
    }
}

class HomeViewController: UIViewController, HomeDisplayLogic {
    var interactor: HomeBusinessLogic?
    var themes: [ContentMovie] = []
    var movies: [DetailedContent] = []
    var popularMoviesList: [DetailedContent] = []
    private var stopPagination = false
    
    struct Layout {}
    
    // MARK: Layout
    lazy var containerView: UIStackView = {
        let stack = UIStackView()
        stack.alignment = .center
        stack.spacing = Layout.ComponentSizes.distance.rawValue
        stack.distribution = .fill
        stack.axis = .vertical
        stack.translatesAutoresizingMaskIntoConstraints = false
        return stack
    }()
    
    lazy var headerView: UIView = {
        let view = UIView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    lazy var titlePage: UILabel = {
        let lbl = UILabel()
        lbl.text = HomeStrings.titleText.localized()
        lbl.numberOfLines = 0
        lbl.font = UIFont.Inter(.bold, size: Layout.FontSize.large.rawValue)
        lbl.textColor = .white
        lbl.translatesAutoresizingMaskIntoConstraints = false
        return lbl
    }()
    
    lazy var profileImage: UIImageView = {
        let imageView = UIImageView(frame: CGRect(x: .zero, y: .zero, width: 40, height: 40))
        let image = UIImage(named: "profile_bob")
        imageView.contentMode = .scaleToFill
        imageView.layer.borderWidth = 1.0
        imageView.layer.masksToBounds = false
        imageView.layer.borderColor = UIColor.white.cgColor
        imageView.layer.cornerRadius = imageView.frame.size.height / 2
        imageView.clipsToBounds = true
        imageView.image = image
        imageView.translatesAutoresizingMaskIntoConstraints = false
        
        return imageView
    }()
    
    lazy var textField: UITextField = {
        let tf = UITextField()
        let placeholderText = HomeStrings.searchTitle.localized()
        let placeholderColor = UIColor.lightGray
        let attributes = [NSAttributedString.Key.foregroundColor: placeholderColor]
        let attributedPlaceholder = NSAttributedString(string: placeholderText, attributes: attributes)
        tf.attributedPlaceholder = attributedPlaceholder
        tf.font = UIFont.Inter(.semiBold, size: Layout.FontSize.small.rawValue)
        tf.textColor = .white
        tf.borderStyle = UITextField.BorderStyle.roundedRect
        tf.autocorrectionType = UITextAutocorrectionType.no
        tf.keyboardType = UIKeyboardType.default
        tf.returnKeyType = UIReturnKeyType.done
        tf.clearButtonMode = .whileEditing
        tf.tintColor = .gray
        tf.contentVerticalAlignment = UIControl.ContentVerticalAlignment.center
        tf.translatesAutoresizingMaskIntoConstraints = false
        tf.backgroundColor = UIColor(red: 0.21, green: 0.03, blue: 0.42, alpha: 1.00)
        
        let symbolConfig = UIImage.SymbolConfiguration(pointSize: 20, weight: .light)
        let symbolImage = UIImage(systemName: "magnifyingglass", withConfiguration: symbolConfig)?.withTintColor(.gray, renderingMode: .alwaysOriginal)
        let imageView = UIImageView(image: symbolImage)
        tf.leftView = imageView
        tf.leftViewMode = .always
        return tf
    }()
    
    lazy var themePills: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .horizontal
        let cv = UICollectionView(frame: .zero, collectionViewLayout: layout)
        cv.showsHorizontalScrollIndicator = false
        cv.translatesAutoresizingMaskIntoConstraints = false
        cv.register(ThemePillsCell.self, forCellWithReuseIdentifier: ThemePillsCell.identifier)
        cv.backgroundColor = .clear
        return cv
    }()
        
    lazy var contentBanner: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .vertical
        let cv = UICollectionView(frame: .zero, collectionViewLayout: layout)
        cv.showsHorizontalScrollIndicator = true
        cv.translatesAutoresizingMaskIntoConstraints = false
        cv.register(MovieBannerCell.self, forCellWithReuseIdentifier: MovieBannerCell.identifier)
        cv.backgroundColor = .clear
        cv.contentInsetAdjustmentBehavior = .never
        return cv
    }()
        
    override func viewDidLoad() {
        super.viewDidLoad()
        configureView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        view.endEditing(true)
        super.touchesBegan(touches, with: event)
    }
    
    // MARK: configure view
    
    func configureView() {
        interactor?.getContent()
        themePills.dataSource = self
        themePills.delegate = self
        
        contentBanner.dataSource = self
        contentBanner.delegate = self
        
        let gradientLayer = CAGradientLayer()
        gradientLayer.frame = view.bounds
        gradientLayer.colors = [UIColor(red: 0.50, green: 0.00, blue: 1.00, alpha: 1.00).cgColor,
                                UIColor(red: 0.00, green: 0.00, blue: 0.00, alpha: 1.00).cgColor]
        view.layer.addSublayer(gradientLayer)
        self.navigationController?.isNavigationBarHidden = true
        setupLayout()
        interactor?.getMovieThemes()
    }
    
    //MARK: - Display methods
    
    func displayFilterOptions(viewModel: Home.MovieGenderFilter.ViewModel) {
        themes = viewModel.movies
        themePills.reloadData()
    }
    
    func displayClickedPill(viewModel: Home.MovieGenderFilter.ViewModel) {
        themes = viewModel.movies
        themePills.reloadData()
    }
    
    func displayBanner(viewModel: Home.MovieBanner.ViewModel) {
        DispatchQueue.main.async { [weak self] in
            guard let self else { return }
            self.movies = viewModel.images
            self.contentBanner.reloadData()
        }
    }
    
    func displayStopPagination(viewModel: Home.Pagination.ViewModel) {
        stopPagination = true
    }
}

extension HomeViewController {
    private func setupLayout() {
        view.addSubview(containerView)
        containerView.addArrangedSubview(headerView)
        headerView.addSubview(titlePage)
        headerView.addSubview(profileImage)
        containerView.addArrangedSubview(textField)
        containerView.addArrangedSubview(themePills)
        containerView.addArrangedSubview(contentBanner)
        
        NSLayoutConstraint.activate([
            containerView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            containerView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            containerView.topAnchor.constraint(equalTo: view.topAnchor),
            containerView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            
            headerView.topAnchor.constraint(equalTo: containerView.topAnchor, constant: 64),
            headerView.leadingAnchor.constraint(equalTo: containerView.leadingAnchor, constant: 16),
            headerView.trailingAnchor.constraint(equalTo: containerView.trailingAnchor, constant: -16),
            
            titlePage.topAnchor.constraint(equalTo: headerView.topAnchor),
            titlePage.leadingAnchor.constraint(equalTo: headerView.leadingAnchor),
            titlePage.bottomAnchor.constraint(equalTo: headerView.bottomAnchor),
            
            profileImage.centerYAnchor.constraint(equalTo: titlePage.centerYAnchor),
            profileImage.leadingAnchor.constraint(equalTo: titlePage.trailingAnchor, constant: 56),
            profileImage.trailingAnchor.constraint(equalTo: headerView.trailingAnchor),
            profileImage.heightAnchor.constraint(equalToConstant: 40),
            profileImage.widthAnchor.constraint(equalToConstant: 40),
            
            textField.trailingAnchor.constraint(equalTo: containerView.trailingAnchor, constant: -16),
            textField.leadingAnchor.constraint(equalTo: containerView.leadingAnchor, constant: 16),

            themePills.trailingAnchor.constraint(equalTo: containerView.trailingAnchor),
            themePills.leadingAnchor.constraint(equalTo: textField.leadingAnchor),
            themePills.heightAnchor.constraint(equalToConstant: Layout.ComponentSizes.pillsHeight.rawValue),

            contentBanner.trailingAnchor.constraint(equalTo: containerView.trailingAnchor,
                                                    constant: -16),
            contentBanner.leadingAnchor.constraint(equalTo: containerView.leadingAnchor,
                                                   constant: 16),
        ])
    }
}

extension HomeViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIScrollViewDelegate {
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        if collectionView == themePills {
            return CGSize(width: themes[indexPath.item].gender.size(withAttributes: [NSAttributedString.Key.font : UIFont.Inter(.semiBold, size: Layout.FontSize.small.rawValue)]).width + 33, height: 30)
        } else {
            return CGSize(width: 156, height: 220)
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
        return .zero
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if collectionView == themePills {
            return themes.count
        }
        return movies.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        if collectionView == themePills {
            guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ThemePillsCell.identifier, for: indexPath) as? ThemePillsCell else { return UICollectionViewCell() }
            cell.layer.cornerRadius = cell.frame.height / 2
            cell.layer.masksToBounds = true
            cell.setupCell(content: themes[indexPath.row])
            
            return cell
        }
        
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MovieBannerCell.identifier, for: indexPath) as? MovieBannerCell else { return UICollectionViewCell() }
        let movie = movies[indexPath.row]
        if cell.movieImage.image == nil {
            cell.setupCell(content: movie.posterPath ?? "")
        }
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if collectionView == themePills {
            interactor?.changeSelectedItem(request: Home.MovieGenderFilter.Request(indexClicked: indexPath.row))
            return
        }
        
        let contentRef = movies[indexPath.row]
        interactor?.goesToDetail(content: contentRef)
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let height = scrollView.frame.size.height
        let contentYOffset = scrollView.contentOffset.y
        let distanceFromBottom = scrollView.contentSize.height - contentYOffset
        
        if distanceFromBottom < height && !stopPagination {
            interactor?.loadMoreItems()
        }
    }
}
